// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAchNpfU4cqemcuI3vOLx8kdXqTWizdFL8',
    appId: '1:994216544031:web:77054635fa59e8c55ed22a',
    messagingSenderId: '994216544031',
    projectId: 'smart-irigation-8c3e8',
    authDomain: 'smart-irigation-8c3e8.firebaseapp.com',
    databaseURL: 'https://smart-irigation-8c3e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-irigation-8c3e8.firebasestorage.app',
    measurementId: 'G-T2CT7TJELZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi0OB7-6DkMWGF5aaS3GG7DW-IPaeJtzU',
    appId: '1:994216544031:android:fc365e50a9a4ed005ed22a',
    messagingSenderId: '994216544031',
    projectId: 'smart-irigation-8c3e8',
    databaseURL: 'https://smart-irigation-8c3e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-irigation-8c3e8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAchNpfU4cqemcuI3vOLx8kdXqTWizdFL8',
    appId: '1:994216544031:web:515c7044543533365ed22a',
    messagingSenderId: '994216544031',
    projectId: 'smart-irigation-8c3e8',
    authDomain: 'smart-irigation-8c3e8.firebaseapp.com',
    databaseURL: 'https://smart-irigation-8c3e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-irigation-8c3e8.firebasestorage.app',
    measurementId: 'G-2QJ0RM8D32',
  );

}